[project]
name = "cnn"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "keras>=3.11.3",
    "numpy>=2.3.4",
    "tensorflow>=2.20.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
    "ipywidgets>=8.1.7",
]
plot = [
    "matplotlib>=3.10.7",
]
